# 2023-02-12

# https://docs.github.com/rest/reference/actions#create-a-workflow-dispatch-event'

name: "triggered-02"

# on:
#   push:
#     branches: [ "main" ]
on: workflow_dispatch

jobs:
  Triggered:
    name: Triggered Workflow
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -ux
          echo "I have been successfully triggered!"
